# script_template: "custom-inno-setup-script.iss"
app_id: 15F38A1C-4C4B-4477-99C3-1205BC28C4CC
publisher_name: LeanFlutter
publisher_url: https://github.com/leanflutter/flutter_distributor
display_name: Hello 世界
create_desktop_icon: true
launch_at_startup: true
# install_dir_name: "D:\\HELLO-WORLD"
# Custom Inno Setup path (optional, defaults to "C:\Program Files (x86)\Inno Setup 6")
# inno_setup_path: "D:\Tools\Inno Setup 6"
locales:
  - zh
